import * as React from 'react';
import { createRoot } from 'react-dom/client'
import App from './App'
import '@fontsource/merriweather/400.css'
import '@fontsource/merriweather/700.css'
import '@fontsource/merriweather/900.css'
import '@fontsource/ibm-plex-sans/400.css'
import '@fontsource/ibm-plex-sans/500.css'
import '@fontsource/ibm-plex-sans/600.css'
import '@fontsource/ibm-plex-sans/700.css'
import '@fontsource/merriweather/cyrillic-400.css'
import '@fontsource/merriweather/cyrillic-700.css'
import '@fontsource/merriweather/cyrillic-900.css'
import '@fontsource/ibm-plex-sans/cyrillic-400.css'
import '@fontsource/ibm-plex-sans/cyrillic-500.css'
import '@fontsource/ibm-plex-sans/cyrillic-600.css'
import '@fontsource/ibm-plex-sans/cyrillic-700.css'
import './index.css'

createRoot(document.getElementById("root")!).render(<App />);